networks:
  account-center:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: br0

services:
  app:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/default.conf
      - certbot_www:/vol/www
      - certbot_certs:/etc/letsencrypt
    env_file:
      - .env
    environment:
      - APP_ENV=${APP_ENV}
      - NGINX_SERVER_NAME=${NGINX_SERVER_NAME}
      - NGINX_ROOT=${NGINX_ROOT}
      - CORS_ALLOW_ORIGIN=${CORS_ALLOW_ORIGIN}
      - SSL_CERTIFICATE=/etc/letsencrypt/live/${CERTBOT_DOMAIN}/fullchain.pem
      - SSL_CERTIFICATE_KEY=/etc/letsencrypt/live/${CERTBOT_DOMAIN}/privkey.pem
    depends_on:
      - php
      - redis
      - mysql
    networks:
      - account-center

  certbot:
    build:
      context: ./certbot
    container_name: certbot
    env_file:
      - .env
    environment:
      - CERTBOT_DOMAIN=${CERTBOT_DOMAIN}
      - CERTBOT_EMAIL=${CERTBOT_EMAIL}
      - CERTBOT_STAGING=${CERTBOT_STAGING}
    volumes:
      - certbot_www:/vol/www/
      - certbot_certs:/etc/letsencrypt/
    depends_on:
      - app
    restart: "no"
    networks:
      - account-center


  mysql:
    image: mariadb:10.6
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: account-center
      MYSQL_USER: account-center
      MYSQL_PASSWORD: 12346789
      MYSQL_ROOT_PASSWORD: 12346789
      #      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./db/mysql:/var/lib/mysql
      - ./db/init:/docker-entrypoint-initdb.d
    networks:
      - account-center

  php:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "9000"
    environment:
      CONTAINER_ROLE: app
      APP_ENV: local
    volumes:
      - ./src:/var/www/html:delegated
    env_file:
      - ./src/.env
    depends_on:
      - redis
      - mysql
    networks:
      - account-center

  queue:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www/html:delegated
    environment:
      APP_ENV: local
      CONTAINER_ROLE: queue
    command: /usr/local/bin/start
    restart: unless-stopped
    #    env_file:
    #      - ./.env
    depends_on:
      - php
      - redis
      - mysql
    networks:
      - account-center

  redis:
    image: redis:alpine
    restart: unless-stopped
    expose:
      - "6379"
    command: redis-server --appendonly yes --replica-read-only no --save 60 1 --loglevel warning
    volumes:
      - redis-data:/data
    networks:
      - account-center

  composer:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www/html
    depends_on:
      - php
    entrypoint: [ 'composer', '--ignore-platform-reqs' ]
    networks:
      - account-center

  npm:
    image: node:current-alpine
    volumes:
      - ./src:/var/www/html
    ports:
      - "3000:3000"
      - "3001:3001"
      - "5173:5173"
    working_dir: /var/www/html
    entrypoint: [ 'npm' ]
    networks:
      - account-center

  artisan:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www/html:delegated
    depends_on:
      - php
      - mysql
    entrypoint: [ 'php', '/var/www/html/artisan' ]
    networks:
      - account-center

  mailpit:
    image: axllent/mailpit
    restart: unless-stopped
    volumes:
      - ./data:/data
    ports:
      - 8025:8025
      - 1025:1025
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATABASE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
    networks:
      - account-center

#  minio:
#    image: minio/minio:latest
#    command: server /data --console-address ":9001"
#    volumes:
#      - ./data/minio/dev:/data
#    environment:
#      MINIO_ROOT_USER: account-center
#      MINIO_ROOT_PASSWORD: 123456789
#    ports:
#      - "9002:9000"
#      - "9001:9001"
#    restart: unless-stopped
#    networks:
#      - account-center
volumes:
  redis-data:
  certbot_www:
  certbot_certs:
